/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStentInvoicesRouteImport } from './routes/app/stent-invoices'
import { Route as AppProductsRouteImport } from './routes/app/products'
import { Route as AppMyDetailsRouteImport } from './routes/app/my-details'
import { Route as AppInvoicesRouteImport } from './routes/app/invoices'
import { Route as AppDeliveryChallansRouteImport } from './routes/app/delivery-challans'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppBuyersRouteImport } from './routes/app/buyers'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStentInvoicesRoute = AppStentInvoicesRouteImport.update({
  id: '/stent-invoices',
  path: '/stent-invoices',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMyDetailsRoute = AppMyDetailsRouteImport.update({
  id: '/my-details',
  path: '/my-details',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDeliveryChallansRoute = AppDeliveryChallansRouteImport.update({
  id: '/delivery-challans',
  path: '/delivery-challans',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBuyersRoute = AppBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/app/buyers': typeof AppBuyersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/delivery-challans': typeof AppDeliveryChallansRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/my-details': typeof AppMyDetailsRoute
  '/app/products': typeof AppProductsRoute
  '/app/stent-invoices': typeof AppStentInvoicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/app/buyers': typeof AppBuyersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/delivery-challans': typeof AppDeliveryChallansRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/my-details': typeof AppMyDetailsRoute
  '/app/products': typeof AppProductsRoute
  '/app/stent-invoices': typeof AppStentInvoicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/app/buyers': typeof AppBuyersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/delivery-challans': typeof AppDeliveryChallansRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/my-details': typeof AppMyDetailsRoute
  '/app/products': typeof AppProductsRoute
  '/app/stent-invoices': typeof AppStentInvoicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/app/buyers'
    | '/app/dashboard'
    | '/app/delivery-challans'
    | '/app/invoices'
    | '/app/my-details'
    | '/app/products'
    | '/app/stent-invoices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/app/buyers'
    | '/app/dashboard'
    | '/app/delivery-challans'
    | '/app/invoices'
    | '/app/my-details'
    | '/app/products'
    | '/app/stent-invoices'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/app/buyers'
    | '/app/dashboard'
    | '/app/delivery-challans'
    | '/app/invoices'
    | '/app/my-details'
    | '/app/products'
    | '/app/stent-invoices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/stent-invoices': {
      id: '/app/stent-invoices'
      path: '/stent-invoices'
      fullPath: '/app/stent-invoices'
      preLoaderRoute: typeof AppStentInvoicesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/my-details': {
      id: '/app/my-details'
      path: '/my-details'
      fullPath: '/app/my-details'
      preLoaderRoute: typeof AppMyDetailsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/delivery-challans': {
      id: '/app/delivery-challans'
      path: '/delivery-challans'
      fullPath: '/app/delivery-challans'
      preLoaderRoute: typeof AppDeliveryChallansRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/buyers': {
      id: '/app/buyers'
      path: '/buyers'
      fullPath: '/app/buyers'
      preLoaderRoute: typeof AppBuyersRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppBuyersRoute: typeof AppBuyersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeliveryChallansRoute: typeof AppDeliveryChallansRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppMyDetailsRoute: typeof AppMyDetailsRoute
  AppProductsRoute: typeof AppProductsRoute
  AppStentInvoicesRoute: typeof AppStentInvoicesRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBuyersRoute: AppBuyersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDeliveryChallansRoute: AppDeliveryChallansRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppMyDetailsRoute: AppMyDetailsRoute,
  AppProductsRoute: AppProductsRoute,
  AppStentInvoicesRoute: AppStentInvoicesRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
